import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  main: {
    flex: 1,
    backgroundColor: '#090E1F',
  },
  scroll: {
    flex: 1,
    paddingHorizontal: 14,
  },
  topo: {
    marginTop: 52,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  perfilBtn: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#8A68FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  avatarText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 12,
  },
  saudacao: {
    color: '#7F8AB7',
    fontSize: 10,
    fontWeight: '700',
  },
  perfilNome: {
    color: '#F4F6FF',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 24,
  },
  helpBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: '#27315B',
    backgroundColor: '#111832',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buscaWrapper: {
    height: 44,
    borderRadius: 12,
    backgroundColor: '#111832',
    borderWidth: 1,
    borderColor: '#27315B',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    marginBottom: 14,
  },
  buscaInput: {
    flex: 1,
    color: '#E6EAFF',
    marginLeft: 8,
    fontSize: 13,
    fontWeight: '600',
  },
  sectionHeading: {
    color: '#8F98C2',
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 0.4,
    marginBottom: 10,
  },
  progressoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  progressoCard: {
    width: '48.5%',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  progressoCardRoxo: {
    backgroundColor: '#1A1C4A',
    borderColor: '#4850AE',
  },
  progressoCardLaranja: {
    backgroundColor: '#2A1F19',
    borderColor: '#A56A2A',
  },
  progressoLabel: {
    color: '#AEB5DA',
    fontSize: 10,
    fontWeight: '700',
  },
  progressoValor: {
    color: '#FFFFFF',
    fontSize: 30,
    fontWeight: '900',
    lineHeight: 34,
    marginTop: 2,
  },
  progressoMeta: {
    color: '#8E97C4',
    fontSize: 10,
    fontWeight: '700',
  },
  progressoLinha: {
    marginTop: 8,
    height: 4,
    width: '100%',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 999,
    overflow: 'hidden',
  },
  progressoLinhaFill: {
    height: '100%',
    backgroundColor: '#F59E0B',
    borderRadius: 999,
  },
  vazio: {
    color: '#7F89B0',
    fontSize: 13,
    marginTop: 2,
    marginLeft: 2,
  },
  scrollBottomSpace: {
    height: 86,
  },
  bottomBar: {
    position: 'absolute',
    left: 10,
    right: 10,
    bottom: 10,
    height: 64,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#28315B',
    backgroundColor: '#0D1330',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 56,
  },
  navIcon: {
    color: '#7682B4',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 3,
  },
  navLabel: {
    color: '#707AA8',
    fontSize: 10,
    fontWeight: '700',
  },
  navLabelActive: {
    color: '#7F6CFF',
  },
  navItemPlus: {
    marginTop: -8,
  },
  navPlusText: {
    color: '#FFFFFF',
    fontSize: 20,
    width: 34,
    height: 34,
    borderRadius: 17,
    textAlign: 'center',
    lineHeight: 33,
    overflow: 'hidden',
    backgroundColor: '#6F52FF',
    marginBottom: 3,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.62)',
    justifyContent: 'flex-end',
  },
  modalBox: {
    backgroundColor: '#151D3A',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 22,
    paddingBottom: 30,
    borderTopWidth: 1,
    borderColor: '#2A3564',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  modalTitulo: {
    color: '#F4F6FF',
    fontSize: 20,
    fontWeight: '800',
  },
  modalLabel: {
    color: '#AAB6D9',
    marginBottom: 8,
    fontSize: 13,
    fontWeight: '600',
  },
  modalInput: {
    backgroundColor: '#1B2545',
    borderWidth: 1,
    borderColor: '#303E70',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#FFFFFF',
    marginBottom: 14,
    fontSize: 14,
  },
  topicoInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  topicoInputField: {
    flex: 1,
    marginBottom: 0,
    marginRight: 8,
  },
  topicoAddBtn: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: '#6F52FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topicoAddBtnDisabled: {
    opacity: 0.35,
  },
  topicoAddBtnText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '700',
  },
  topicoChipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 10,
  },
  topicoChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1B2545',
    borderWidth: 1,
    borderColor: '#303E70',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 6,
    marginBottom: 6,
  },
  topicoChipText: {
    color: '#C0CAE8',
    fontSize: 13,
    fontWeight: '600',
    marginRight: 6,
  },
  topicoChipRemove: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topicoChipRemoveText: {
    color: '#8a9bb5',
    fontSize: 10,
    fontWeight: '700',
  },
  topicoCheckRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 2,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#4A5A8A',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  checkboxChecked: {
    backgroundColor: '#2DD4BF',
    borderColor: '#2DD4BF',
  },
  checkboxIcon: {
    color: '#0a0f1e',
    fontSize: 14,
    fontWeight: '800',
  },
  topicoCheckLabel: {
    color: '#E6EAFF',
    fontSize: 15,
    fontWeight: '600',
    flex: 1,
  },
  topicoCheckLabelDone: {
    color: '#6a7a8a',
    textDecorationLine: 'line-through',
  },
  modalConfirmar: {
    backgroundColor: '#6F52FF',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 6,
  },
  modalConfirmarText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 15,
  },
  excluirBtn: {
    backgroundColor: '#D23A3A',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 10,
  },
  excluirBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
});
