import { StyleSheet } from 'react-native';

export const CreateMateriaModalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.62)',
    justifyContent: 'flex-end',
  },
  modalBox: {
    backgroundColor: '#151D3A',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 22,
    paddingBottom: 30,
    borderTopWidth: 1,
    borderColor: '#2A3564',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  modalTitulo: {
    color: '#F4F6FF',
    fontSize: 20,
    fontWeight: '800',
  },
  modalClose: {
    color: '#5a6a7a',
    fontSize: 20,
  },
  modalLabel: {
    color: '#AAB6D9',
    marginBottom: 8,
    fontSize: 13,
    fontWeight: '600',
  },
  modalInput: {
    backgroundColor: '#1B2545',
    borderWidth: 1,
    borderColor: '#303E70',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#FFFFFF',
    marginBottom: 14,
    fontSize: 14,
  },
  topicoInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  topicoInputField: {
    flex: 1,
    marginBottom: 0,
    marginRight: 8,
  },
  topicoAddBtn: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: '#6F52FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topicoAddBtnDisabled: {
    opacity: 0.35,
  },
  topicoAddBtnText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '700',
  },
  topicoChipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 10,
  },
  topicoChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1B2545',
    borderWidth: 1,
    borderColor: '#303E70',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 6,
    marginBottom: 6,
  },
  topicoChipText: {
    color: '#C0CAE8',
    fontSize: 13,
    fontWeight: '600',
    marginRight: 6,
  },
  topicoChipRemove: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topicoChipRemoveText: {
    color: '#8a9bb5',
    fontSize: 10,
    fontWeight: '700',
  },
  modalConfirmar: {
    backgroundColor: '#6F52FF',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 6,
  },
  modalConfirmarText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 15,
  },
});