import { StyleSheet } from 'react-native';

export const ProfileScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0f1e',
  },
  gradientFill: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  glowOrb1: {
    position: 'absolute',
    top: -80,
    right: -60,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: '#5ab8d4',
    opacity: 0.08,
  },
  glowOrb2: {
    position: 'absolute',
    bottom: 100,
    left: -80,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: '#3a9ab8',
    opacity: 0.06,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 10,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  backButtonText: {
    color: '#8a9bb5',
    fontSize: 22,
  },
  headerTitle: {
    color: '#e8edf5',
    fontSize: 22,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  profileHeader: {
    alignItems: 'center',
    paddingVertical: 24,
    paddingHorizontal: 20,
  },
  avatarCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#5ab8d4',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  avatarInitials: {
    color: '#0a0f1e',
    fontSize: 32,
    fontWeight: '700',
  },
  userEmail: {
    color: '#8a9bb5',
    fontSize: 15,
    letterSpacing: 0.3,
  },
  cardsContainer: {
    paddingHorizontal: 20,
    marginTop: 8,
  },
  cardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  card: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    padding: 20,
    alignItems: 'center',
    marginHorizontal: 6,
  },
  cardIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  cardIcon: {
    fontSize: 20,
  },
  cardValue: {
    color: '#e8edf5',
    fontSize: 26,
    fontWeight: '700',
  },
  cardLabel: {
    color: '#6a7a8a',
    fontSize: 12,
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  sairContainer: {
    alignItems: 'center',
    marginTop: 40,
    marginBottom: 40,
    gap: 16,
  },
  sairButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 36,
    borderRadius: 12,
    backgroundColor: 'rgba(255,69,58,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,69,58,0.25)',
  },
  sairButtonText: {
    color: '#ff453a',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  historicoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 36,
    borderRadius: 12,
    backgroundColor: 'rgba(90,184,212,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(90,184,212,0.25)',
  },
  historicoButtonText: {
    color: '#5ab8d4',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
});
