import { StyleSheet } from 'react-native';

export const ProfileScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#090E1F',
  },
  gradientFill: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  glowOrb1: {
    position: 'absolute',
    top: -80,
    right: -60,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: '#5ab8d4',
    opacity: 0.08,
  },
  glowOrb2: {
    position: 'absolute',
    bottom: 100,
    left: -80,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: '#3a9ab8',
    opacity: 0.06,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 10,
    position: 'relative',
  },
  backButton: {
    position: 'absolute',
    left: 20,
    top: 46,
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#27315B',
    backgroundColor: '#111832',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: {
    color: '#7F8AB7',
    fontSize: 22,
  },
  headerTitle: {
    color: '#F4F6FF',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  editButton: {
    position: 'absolute',
    right: 20,
    top: 46,
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#27315B',
    backgroundColor: '#111832',
    alignItems: 'center',
    justifyContent: 'center',
  },
  editText: {
    color: '#7F8AB7',
    fontSize: 18,
  },

  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },

  profileHeader: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  avatarCircle: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#8A68FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
    borderWidth: 3,
    borderColor: 'rgba(138,104,255,0.3)',
  },
  avatarInitials: {
    color: '#FFFFFF',
    fontSize: 36,
    fontWeight: '700',
  },
  userName: {
    color: '#F4F6FF',
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 4,
  },
  userEmail: {
    color: '#7F8AB7',
    fontSize: 13,
    letterSpacing: 0.3,
    marginBottom: 10,
  },
  badgePill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(111,82,255,0.12)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(111,82,255,0.25)',
    paddingVertical: 5,
    paddingHorizontal: 14,
  },
  badgeText: {
    color: '#8A68FF',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.3,
  },

  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
    marginBottom: 28,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#111832',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#27315B',
    paddingVertical: 16,
    alignItems: 'center',
    marginHorizontal: 4,
  },
  statValue: {
    color: '#F4F6FF',
    fontSize: 22,
    fontWeight: '700',
  },
  statLabel: {
    color: '#8E97C4',
    fontSize: 11,
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginTop: 4,
  },

  sectionTitle: {
    color: '#8F98C2',
    fontSize: 13,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 14,
  },
  progressoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 28,
  },
  progressoCard: {
    flex: 1,
    backgroundColor: '#111832',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#27315B',
    padding: 16,
    marginHorizontal: 4,
  },
  progressoCardAccent: {
    borderColor: 'rgba(111,82,255,0.3)',
  },
  progressoCardAccent2: {
    borderColor: 'rgba(212,160,90,0.3)',
  },
  progressoCardLabel: {
    color: '#7F8AB7',
    fontSize: 12,
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  progressoCardValue: {
    color: '#F4F6FF',
    fontSize: 28,
    fontWeight: '700',
  },
  progressoCardSub: {
    color: '#7F8AB7',
    fontSize: 12,
    marginTop: 4,
  },
  progressoCardSubRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },

  buttonsContainer: {
    marginTop: 16,
    gap: 12,
  },
  historicoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 36,
    borderRadius: 12,
    backgroundColor: 'rgba(111,82,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(111,82,255,0.25)',
  },
  historicoButtonText: {
    color: '#8A68FF',
    fontSize: 15,
    fontWeight: '600',
    marginLeft: 8,
  },
  sairButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 36,
    borderRadius: 12,
    backgroundColor: 'rgba(210,58,58,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(210,58,58,0.25)',
  },
  sairButtonText: {
    color: '#D23A3A',
    fontSize: 15,
    fontWeight: '600',
    marginLeft: 8,
  },
});
