import { StyleSheet } from 'react-native';

export const ProfileScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0f1e',
  },
  gradientFill: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  glowOrb1: {
    position: 'absolute',
    top: -50,
    right: -50,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(111, 82, 255, 0.2)',
    filter: 'blur(40px)',
  },
  glowOrb2: {
    position: 'absolute',
    bottom: -30,
    left: -30,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'rgba(111, 82, 255, 0.15)',
    filter: 'blur(40px)',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#27315B',
    backgroundColor: '#111832',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  backButtonText: {
    color: '#7F8AB7',
    fontSize: 22,
  },
  headerTitle: {
    color: '#F4F6FF',
    fontSize: 20,
    fontWeight: '700',
    flex: 1,
  },
  editButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(111, 82, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  editText: {
    color: '#F4F6FF',
    fontSize: 18,
  },
  profileHeader: {
    alignItems: 'center',
    paddingVertical: 30,
    paddingHorizontal: 20,
  },
  avatarCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 3,
    borderColor: '#6F52FF',
    backgroundColor: '#151D3A',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    position: 'relative',
  },
  avatarInitials: {
    color: '#F4F6FF',
    fontSize: 36,
    fontWeight: '700',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 50,
  },
  editAvatarButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#6F52FF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#090E1F',
  },
  editAvatarText: {
    color: '#F4F6FF',
    fontSize: 18,
  },
  userName: {
    color: '#F4F6FF',
    fontSize: 24,
    fontWeight: '700',
    marginTop: 15,
  },
  userEmail: {
    color: '#8E97C4',
    fontSize: 16,
    marginTop: 5,
  },
  badgePill: {
    backgroundColor: 'rgba(111, 82, 255, 0.2)',
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginTop: 15,
  },
  badgeText: {
    color: '#8A68FF',
    fontSize: 14,
    fontWeight: '600',
  },
  statsRow: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginTop: 20,
    marginBottom: 20,
  },
  statCard: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#111832',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#27315B',
    paddingVertical: 16,
    marginHorizontal: 6,
  },
  statValue: {
    color: '#F4F6FF',
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 4,
  },
  statLabel: {
    color: '#8E97C4',
    fontSize: 12,
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  sectionTitle: {
    color: '#8F98C2',
    fontSize: 14,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginHorizontal: 20,
    marginBottom: 12,
  },
  progressoRow: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  progressoCard: {
    flex: 1,
    backgroundColor: '#111832',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#27315B',
    padding: 16,
    marginHorizontal: 6,
  },
  progressoCardAccent: {
    backgroundColor: 'rgba(111, 82, 255, 0.15)',
    borderColor: '#6F52FF',
  },
  progressoCardAccent2: {
    backgroundColor: 'rgba(111, 82, 255, 0.1)',
    borderColor: '#6F52FF',
  },
  progressoCardLabel: {
    color: '#8F98C2',
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  progressoCardValue: {
    color: '#F4F6FF',
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 4,
  },
  progressoCardSub: {
    color: '#8E97C4',
    fontSize: 13,
  },
  progressoCardSubRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  buttonsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginTop: 20,
    marginBottom: 20,
    gap: 12,
  },
  historicoButton: {
    flex: 1,
    backgroundColor: '#111832',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#27315B',
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historicoButtonText: {
    color: '#F4F6FF',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 6,
  },
  sairButton: {
    flex: 1,
    backgroundColor: '#2A1B1B',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#5A3030',
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sairButtonText: {
    color: '#F4F6FF',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 6,
  },
  scrollView: {
    flex: 1,
  },
  flameEmoji: {
    fontSize: 22,
  },
  buttonEmoji: {
    fontSize: 18,
  },
});